apiVersion: v1
kind: Service
metadata:
  name: assign2
  namespace: anamdari
  labels:
    app: assign2
spec:
  ports:
  - port: 8080
    name: assign2
    protocol: TCP
    targetPort: 8080
  selector:
    app: assign2
  type: NodePort